version: '3'  #파일 규격 버전

services: #실행하려는 컨테이너들을 정의
  db: #서비스명
    platform: 'linux/x86_64'
    image: 'mysql:8.0.20' #사용할 이미지
    container_name: mysql_db  #컨테이너 이름 설정
    ports:
      - '3306:3306' #접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: 'Asia/Seoul'
    command:  #명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql/datadir:/var/lib/mysql
